name: go test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Vendor modules for later steps.
        run: |
          go mod vendor
      - name: go unit test
        run: make test
      - name: go integration test
        run: make test-integration

