name: golangci-lint

on:
  push:

env:
  GOPROXY: https://goproxy.githubapp.com/mod,https://proxy.golang.org,direct
  GOPRIVATE: ''
  GONOPROXY: ''
  GONOSUMDB: github.com/github/*

jobs:
  golangci:
    strategy:
      matrix:
        go: ["1.18", "1.19"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Authenticate with goproxy.
        run: |
          echo "machine goproxy.githubapp.com login nobody password ${{ secrets.CONTAINER_BUILDER_TOKEN }}" >> $HOME/.netrc
      - name: Vendor modules for later steps.
        run: |
          go mod vendor
      - uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc # v3.2.0
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.48
